version: '3.8'

services:
  verilator:
    build: .
    image: verilator-gtkwave:latest
    container_name: verilator-dev
    volumes:
      - ./project:/project
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: host
    stdin_open: true
    tty: true
    privileged: true
